### ISSUE TITLE
TB claims insufficient space

### ISSUE THREAD

**Issue by andreas-h** [guillaumev/owncloud_for_filelink#16]
TB preferences show a wrong free disk space.  In reality, I have about 34G free on the server:

    andreas@srv1:~$ df -h .
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/xvda1      197G  154G   34G  83% /

However, TB shows a ridiculously large free amount:

![screenshot from 2015-01-06 22 30 23](https://cloud.githubusercontent.com/assets/358378/5636612/187fb2e0-95f4-11e4-9414-e19820444955.png)

However, when trying to link a file (of ~35M), I get the message that uploading the file would exceed my quota:

![screenshot from 2015-01-06 22 38 09](https://cloud.githubusercontent.com/assets/358378/5636680/d0bea924-95f4-11e4-963b-f18c2035d2ec.png)

**Comment by srsbiz** [comment]
Can you run from terminal
```
curl -X PROPFIND -d '<propfind xmlns="DAV:"><prop><quota-available-bytes/><quota-used-bytes/></prop></propfind>' --basic --user USERNAME:PASSWORD http://SERVER/remote.php/webdav
```

and check if you get something like
```
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
    <d:response>
        <d:href>/remote.php/webdav/</d:href>
        <d:propstat>
            <d:prop>
                <oc:id>0000073452743d957cba9</oc:id>
                <oc:permissions>RDNVCK</oc:permissions>
                <d:quota-available-bytes>472454311936</d:quota-available-bytes>
                <d:quota-used-bytes>60130008064</d:quota-used-bytes>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
```
in response?

**Comment by 7H0MAS** [comment]
Here is the response I've got :
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
   <d:response>
      <d:href>/remote.php/webdav/</d:href>
      <d:propstat>
         <d:prop>
            <oc:id>0000401051d6aef31b152</oc:id>
	    <oc:permissions>RDNVCK</oc:permissions>
            <d:quota-available-bytes>2034163713</d:quota-available-bytes>
            <d:quota-used-bytes>2260803583</d:quota-used-bytes>
         </d:prop>
         <d:status>HTTP/1.1 200 OK</d:status>
      </d:propstat>
   </d:response>
```

**Comment by andreas-h** [comment]
Thanks for your quick answer!  I just checked and got this:

    <?xml version="1.0" encoding="utf-8"?>
    <d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"
xmlns:oc="http://owncloud.org/ns">
      <d:response>
        <d:href>/remote.php/webdav/</d:href>
        <d:propstat>
          <d:prop>
            <oc:id>00000016oc1ce112556e</oc:id>
            <oc:permissions>RDNVCK</oc:permissions>
            <d:quota-available-bytes>35556884480</d:quota-available-bytes>
            <d:quota-used-bytes>48641570862</d:quota-used-bytes>
          </d:prop>
          <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
      </d:response>

**Comment by luckydonald** [comment]
Can confirm this on Mac OS X.
![bildschirmfoto 2015-03-03 um 05 17 22](https://cloud.githubusercontent.com/assets/2737108/6456480/a2392598-c164-11e4-8934-33cf2da00eb9.png)
```
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/webdav/</d:href><d:propstat><d:prop><oc:id>00000013ocktfezdkb59</oc:id><oc:permissions>RDNVCK</oc:permissions><oc:size>16459456387</oc:size><d:quota-available-bytes>5033155601</d:quota-available-bytes><d:quota-used-bytes>16441680879</d:quota-used-bytes></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/webdav/Documents/</d:href><d:propstat><d:prop><oc:id>00000014ocktfezdkb59</oc:id><oc:permissions>RDNVCK</oc:permissions><oc:size>7077385242</oc:size><d:quota-available-bytes>5033155601</d:quota-available-bytes><d:quota-used-bytes>7077385242</d:quota-used-bytes></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/webdav/Music/</d:href><d:propstat><d:prop><oc:id>00000021ocktfezdkb59</oc:id><oc:permissions>RDNVCK</oc:permissions><oc:size>8703687155</oc:size><d:quota-available-bytes>5033155601</d:quota-available-bytes><d:quota-used-bytes>8703687155</d:quota-used-bytes></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/webdav/Photos/</d:href><d:propstat><d:prop><oc:id>00026522ocktfezdkb59</oc:id><oc:permissions>RDNVCK</oc:permissions><oc:size>660608482</oc:size><d:quota-available-bytes>5033155601</d:quota-available-bytes><d:quota-used-bytes>660608482</d:quota-used-bytes></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/webdav/Clipboard/</d:href><d:propstat><d:prop><oc:id>00000377ocktfezdkb59</oc:id><oc:permissions>SRDNVCK</oc:permissions><oc:size>17775508</oc:size><d:quota-available-bytes>107353920868</d:quota-available-bytes><d:quota-used-bytes>17775508</d:quota-used-bytes></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
```
![bildschirmfoto 2015-03-03 um 05 22 00](https://cloud.githubusercontent.com/assets/2737108/6456501/507dbc04-c165-11e4-9601-f0a7d8e6f3b8.png)

**Comment by guillaumev** [comment]
To the ones experiencing this issue: which version of Thunderbird are you using ?

**Comment by andreas-h** [comment]
Thunderbird 31.5.0 on LinuxMint Rebecca (based on Ubuntu 14.04) 64bit

**Comment by 7H0MAS** [comment]
Le 06/03/2015 15:27, Guillaume Viguier-Just a écrit :
>
> To the ones experiencing this issue: which version of Thunderbird are 
> you using ?
>
>
Thunderbird 31.4.0 sous Ubuntu 14.04 64 bits

Merci de votre travail....

Thomas Fleith

**Comment by luckydonald** [comment]
Tbird  31.5.0 (release channel)
OS X, 10.9.5

**Comment by guillaumev** [comment]
Please try 1.2 and let me know: https://addons.mozilla.org/thunderbird/addon/owncloud-for-filelink/versions/

**Comment by andreas-h** [comment]
no change here ...

**Comment by 7H0MAS** [comment]
Le 23/03/2015 15:50, Guillaume Viguier-Just a écrit :
>
> Please try 1.2 and let me know: 
> https://addons.mozilla.org/thunderbird/addon/owncloud-for-filelink/versions/
>
>
Ça fonctionne impeccablement :-)
Merci...

Thomas Fleith

**Comment by luckydonald** [comment]
Nope, Doesn't seem fixed (completely).
![Screenshot without a real name](https://cloud.githubusercontent.com/assets/2737108/6962331/f87b6b6e-d933-11e4-8dfe-516e71fd33db.png)

**Comment by jurgenhaas** [comment]
Same problem here. Ubuntu 15.04, TB 31.7.0, ownCloud for FileLink 1.2

Is it possible that this problem has to do with the fact that my ownCloud server is only available through https?

**Comment by luckydonald** [comment]
Oh, yeah no ```http://``` here too. ```http://``` just forwards every link to ```https://``` version of it.

**Comment by luckydonald** [comment]
@guillaumev  Any progress here?
I find the free storage being ***over 9000*** TB most suspicious.

**Comment by jurgenhaas** [comment]
Still the same problem with TB 38.0.1 and no difference with master of ownCloud for FileLink. Any ideas?

**Comment by neonknight** [comment]
Same problem here with current owncloud_for_filelink master, Icedove (Debian TB rebranding) 31.8.0 on Debian 8.1, using OwnCloud 7.0.4 with https only.

**Comment by gryphius** [comment]
Apparently the code assumes that "quota-available-bytes" is the total storage amount, however, this is the  available storage for additional files ( https://github.com/owncloud/core/wiki/spec:-Quota-handling ). Can someone having this problem check if https://github.com/gryphius/owncloud_for_filelink/commit/82d517d3d6e96a867b8b5617890ca0533bf99eea fixes this?

**Comment by andreas-h** [comment]
> Apparently the code assumes that "quota-available-bytes" is the total
> storage amount, however, this is the available storage for additional
> files ( https://github.com/owncloud/core/wiki/spec:-Quota-handling ).
> Can someone having this problem check if gryphius@82d517d
> <https://github.com/gryphius/owncloud_for_filelink/commit/82d517d3d6e96a867b8b5617890ca0533bf99eea>
> fixes this?

Thanks for possibly having a fix!  Unfortunately, I don't have the
toolchain set up to build TB extensions, I'm a mere user in this case ...

**Comment by gryphius** [comment]
@andreas-h you don't need much of a toolchain. basically you clone/download the repository , zip everything and rename it to .xpi and install it in TB. Make sure the install.rdf is at the root of your zipfile

something like this should do the trick:

```
wget -q https://github.com/gryphius/owncloud_for_filelink/archive/bugfix/quota-handling.zip
unzip -q quota-handling.zip
cd owncloud_for_filelink-bugfix-quota-handling/
zip -rq owncloud-filelink-test *
mv owncloud-filelink-test.zip owncloud-filelink-test.xpi
````

then install the resulting  owncloud-filelink-test.xpi in TB's addon manager. you might have to re-create the owncloud account in your attachment preferences as well.

**Comment by neonknight** [comment]
works for me, thanks @gryphius

**Comment by luckydonald** [comment]
Could somebody who got it working do a pull request?

**Comment by gryphius** [comment]
@luckydonald done: https://github.com/guillaumev/owncloud_for_filelink/pull/35

**Comment by guillaumev** [comment]
Version 1.3 is now published, thank you all for your help on this: https://addons.mozilla.org/en/thunderbird/addon/owncloud-for-filelink/versions/?page=1#version-1.3

**Comment by jurgenhaas** [comment]
Amazing, this is now working great. Thanks everybody.
