### ISSUE TITLE
Files are not being attached, error message

### ISSUE THREAD

**Issue by KingNever** [guillaumev/owncloud_for_filelink#19]
When I try to attach a file with Filelink, the file is being uploaded to ownCloud, but when uploading is finished, Thunderbird gives an error message and doesn´t send the mail. 
When I check ownCloud, the file has been uploaded correctly. 

The error message is saying "Beim Datenaustausch mit ownCloud trat ein unbekannter Fehler auf" (German for something like: "There is an unknown error ocurring when sharing data with ownCloud"). 

I use ownCloud 7.0.1, Thunderbird 31.5 and ownCloud for Filelink 1.1 

As far as I know all settings in ownCloud are ok. (allow apps to use API "yes", allow users to share links "yes", allow public upload "yes" etc.) 
Also the setup of the Thunderbird app should be ok (correct server, username and password), because the file is in ownCloud after Filelink uploaded it. 

Does anyone know a reason for this and how to solve this problem? 

![filelink owncloud error message](https://cloud.githubusercontent.com/assets/11167309/6401519/67b0d6f2-be01-11e4-9700-79fea1cbbd11.JPG)

**Comment by srsbiz** [comment]
Can you turn on debugging (instructions in https://github.com/guillaumev/owncloud_for_filelink/pull/2#issuecomment-32693470) and filter logs for "raw response:"?

**Comment by KingNever** [comment]
Tried to follow the instructions but I don´t have the slightest idea what "Please install 31fc4a1" means or how to do that. When I open that link I see a lot of code and a .js file (that obviously contains the code?!) but I don´t know what to do with it (code noob!!!! ;-)). 

Anyway I succeeded in finding that console in Thunderbird and when receiving the error message there is a comment added: 

[JavaScript Error: "[Exception... "Method not implemented'Method not implemented' when calling method: [nsIAuthPrompt2::asyncPromptAuth]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0"  data: no]"]


I also added that line "Owncloud.logging.console" with value "All" to the about:config but maybe that was senseless when I don´t know what that "Please install 31fc4a1" means and wasn´t able to do that. I noticed that I couldn´t delete that line anymore... any advice?

**Comment by mschmidone** [comment]
Same with version 8 of  OC

**Comment by peterbeck** [comment]
also having this issue with multiple Owncloud 8 instances, filelink for webdav still seems to work, but filelink for owncloud uploads the file, but then shows an unknown error message. 
Tested on Thunderbird Mac (Mavericks) and Icedove on Debian Jessie.

**Comment by guillaumev** [comment]
Ok I haven't tested with OC 8, but with OC 7.0.4 and thunderbird 31 and 31.5, and wasn't able to reproduce the issue... Will keep looking, but would be great if someone could provide more debug messages/information

**Comment by mbiebl** [comment]
@guillaumev: I can reproduce the problem with OC 8.0.2 and TB 31.5.0. OC 7.0.4 worked fine afair.

Here's the log from the debug console with OC 8.0.2. Please note, that the file is actually uploaded. So it seems to fail at the step when getting the share URL.
```
2015-03-12 00:09:35	Owncloud	INFO	uploading inject.py
2015-03-12 00:09:35	Owncloud	INFO	Logging in, aWithUI = true
2015-03-12 00:09:35	Owncloud	INFO	Sending login information...
2015-03-12 00:09:35	Owncloud	INFO	Login information sent!
2015-03-12 00:09:36	Owncloud	INFO	auth token response = {"ocs":{"meta":{"status":"ok","statuscode":100,"message":null},"data":{"person":{"personid":"michael"}}}}
2015-03-12 00:09:36	Owncloud	INFO	statuscode = 100
2015-03-12 00:09:37	Owncloud	INFO	new nsOwncloudFileUploader file = inject.py
2015-03-12 00:09:37	Owncloud	INFO	ready to upload file inject.py to folder /
2015-03-12 00:09:39	Owncloud	DEBUG	Raw formData: shareType=3&path=%2F%2F%2F1426115377061_inject.py
[JavaScript Error: "[Exception... "Method not implemented'Method not implemented' when calling method: [nsIAuthPrompt2::asyncPromptAuth]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0"  data: no]"]
2015-03-12 00:09:40	Owncloud	DEBUG	Raw response: {"ocs":{"meta":{"status":"failure","statuscode":997,"message":"Unauthorised"},"data":[]}}
2015-03-12 00:09:40	Owncloud	INFO	Could not retrive share URL
```

I'm happy to provide more information if needed

**Comment by mbiebl** [comment]
@guillaumev: Thanks for fixing this. Do you have an ETA for the 1.2 release?

**Comment by guillaumev** [comment]
I'd like to get #21 fixed before I release 1.2, but unfortunately I can only work on this addon sporadically...

**Comment by guillaumev** [comment]
FYI 1.2 is released: https://addons.mozilla.org/thunderbird/addon/owncloud-for-filelink/versions/

**Comment by KingNever** [comment]
YES! Now it works! Thank you!!

**Comment by mschmidone** [comment]
The extension is now working flawlessly, also with OC8! Thank you
