### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by Yamakaky** [guillaumev/owncloud_for_filelink#25]
After a first install, I cancelled the configuration, and now it always says me "An error occured while setting up the account". I tried a re-installation. How can I reset the plugin ?

**Comment by Yamakaky** [comment]
I found how to reset the password, using logins.json. Now, I have an other problem : it's stuck at "Checking authorization". Any idea ?
I tried on http and https. It's a fresh install of owncloud 8.

**Comment by guillaumev** [comment]
Closing this. Please try 1.4 and reopen if necessary.

**Comment by Yamakaky** [comment]
Not using owncloud anymore ^^
