### ISSUE TITLE
error uploading file

### ISSUE THREAD

**Issue by quantentunnels** [guillaumev/owncloud_for_filelink#26]
I successfully configured the plugin and everything looks good. When I actually upload a file in the mail composer I get an error. In my ownCloud folder there is a file with the correct filename (plus timestamp in its name) but it seems corrupted somehow as I cannot open it.

**Comment by guillaumev** [comment]
Hi,

Please try version 1.3 that I just published and reopen if needed: https://addons.mozilla.org/en/thunderbird/addon/owncloud-for-filelink/versions/?page=1#version-1.3
