### ISSUE TITLE
complains about upload limit

### ISSUE THREAD

**Issue by sedrubal** [guillaumev/owncloud_for_filelink#27]
When I want to upload something, the plugin complains about owncloud's upload limit, but the limit is large enough and I can upload the same file to oc manually. I think the plugin even does not access the webserver but complaining about the limit.

**Comment by skynet1988** [comment]
Have the same problem here. Owncloud itself is set to upload up to 1gb files, and it does actualy, but the pluggin refuses to upload files more than somewhat 200mb. Is there a solution?

**Comment by chrmarmei** [comment]
For all of you looking for a solution for this problem:
Set a quota for your OC-user.

**Comment by guillaumev** [comment]
Closing this, as this will be fixed in 1.5
