### ISSUE TITLE
Uncommon port

### ISSUE THREAD

**Issue by peterkahl** [guillaumev/owncloud_for_filelink#30]
I am using non-standard port for my ownCloud server.

The upload function works, but the links placed inside the outgoing mails lack the port!!!

Should be:

```
https://sub.domain.tld:XXXXX/....
```

Incorrectly is:

```
https://sub.domain.tld/....
```

Your plugin should have a configuration page to set any custom values.

Thank you!

**Comment by peterkahl** [comment]
Umm. Had to remove the plugin from Thunderbird. Totally useless without a page to configure it.

Will wait for new version, if it becomes available.

**Comment by testingtigerwolf** [comment]
Same issue, useless for me while this issue is not fixed

**Comment by guillaumev** [comment]
Please check if this is still an issue with version 1.4, and with updated versions of owncloud/nextcloud. Feel free to reopen if it is.
