### ISSUE TITLE
Download URL incompatible with ownCloud 8.1

### ISSUE THREAD

**Issue by e-dot** [guillaumev/owncloud_for_filelink#32]
Since upgrade to ownCloud 8.1, all download URLs are broken : the error message is "file not found".

The URL created by owncloud_for_filelink is :
  https://myserver.mycompany.com/owncloud/index.php/s/kzmZljk489o7BPI&download

The working URL (since 8.1) should be:
    https://myserver.mycompany.com/owncloud/index.php/s/kzmZljk489o7BPI/download

**Comment by guillaumev** [comment]
Version 1.3 is now published, thank you for @srsbiz for your help ! https://addons.mozilla.org/en/thunderbird/addon/owncloud-for-filelink/versions/?page=1#version-1.3
