### ISSUE TITLE
Document was not found on the Server - Download link is wrong

### ISSUE THREAD

**Issue by bierdosenhalter** [guillaumev/owncloud_for_filelink#34]
owncloud for filelink 1.2 generates a link like the following:

http://***/owncloud/index.php/s/WWHVhZCSAHhtglg&download

if i try to open it owncloud brings up an error that the document wasnt found on the server

but if i just open

http://***/owncloud/index.php/s/WWHVhZCSAHhtglg

it shows the correct download page with a download link like that

http://***/owncloud/index.php/s/WWHVhZCSAHhtglg/download

im using thunderbird 31.7.0 (german)

**Comment by guillaumev** [comment]
Please try version 1.3 and reopen if needed: https://addons.mozilla.org/en/thunderbird/addon/owncloud-for-filelink/versions/?page=1#version-1.3
