### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by powerriegel** [guillaumev/owncloud_for_filelink#36]
Hello,

on first set up, dialog crashed after entering password. In the thunderbird settings, it asks for autoristation but the button does not help. I deleted all related keys in Ubuntus password storage, but it does not ask for a password anymore. 

I use an uncommon port  and a self-signed certificate. 

Owncloud 8.1.3
Thunderbird 38.3.0
Ubuntu 14.4.2 64bit

Settings for sharing via link and force password are set in owncloud.

**Comment by srsbiz** [comment]
Please see https://github.com/guillaumev/owncloud_for_filelink/issues/8 especially last comment

**Comment by alexanderhaensch** [comment]
Same problem here. I am using LetsEncrypt and Comodo Certificates. It is not a problem with the certificate..

Owncloud 8.2.2
Thunderbird 38.5.1
Ubuntu 15.10 64bit

**Comment by yuniers** [comment]
I'm experiment the same.
Please see [this comment](https://github.com/guillaumev/owncloud_for_filelink/issues/38#issuecomment-176992129)

**Comment by guillaumev** [comment]
Closing this, please try 1.4 and if it doesn't help, feel free to reopen.

**Comment by sjau** [comment]
I just tested with 1.4 using oC 9.0.9, TB 52.1.0 and flielink 1.4 with Let'sEncrypt SSL cert. It works now. Thx for the tool.
