### ISSUE TITLE
Hangs forever "checking authorization"

### ISSUE THREAD

**Issue by callegar** [guillaumev/owncloud_for_filelink#38]
Owncloud server works, you can login from the web nicely
Self signed certificate exception has now been set up in thunderbird
Trying to set up the extension hangs forever.

**Comment by mach-o** [comment]
Experiencing the same issue here.

**Comment by yuniers** [comment]
I have the same error and from error console of Thunderbird I can see.

```
Fecha y hora: 29/01/16 17:00:21
Error: 2016-01-29 17:00:21    Owncloud    ERROR    [Exception... "Component does not have requested interface [nsIRequestObserver.onStopRequest]"  nsresult: "0x80004002 (NS_NOINTERFACE)"  location: "JS frame :: jar:file:///home/dgp/.thunderbird/15wjs3yx.default/extensions/owncloud@viguierjust.com.xpi!/components/nsOwncloud.js :: nsOwncloud_createExistingAccount/successCb< :: line 364"  data: no]

Archivo de origen: resource:///modules/gloda/log4moz.js
Línea: 693

2016-01-29 17:00:21    Owncloud    ERROR    [Exception... "Component does not have requested interface [nsIRequestObserver.onStopRequest]"  nsresult: "0x80004002 (NS_NOINTERFACE)"  location: "JS frame :: jar:file:///home/dgp/.thunderbird/15wjs3yx.default/extensions/owncloud@viguierjust.com.xpi!/components/nsOwncloud.js :: nsOwncloud_createExistingAccount/successCb< :: line 364"  data: no]

Fecha y hora: 29/01/16 17:00:21
Error: NS_NOINTERFACE: Component does not have requested interface [nsIRequestObserver.onStopRequest]
Archivo de origen: jar:file:///home/dgp/.thunderbird/15wjs3yx.default/extensions/owncloud@viguierjust.com.xpi!/components/nsOwncloud.js
Línea: 368

```

**Comment by yuniers** [comment]
After manual cancel of process of verification I clicked "Revocar permisos" and work fine, recognized my allowed size and space used on sever. Too, I can send e-mails with attachments.
During upload process again throw an error but work!
```
Fecha y hora: 29/01/16 17:16:26
Error: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getCharPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource:///modules/cloudFileAccounts.js :: cloudFileAccounts.getDisplayName :: line 207"  data: no]
Archivo de origen: resource:///modules/cloudFileAccounts.js
Línea: 211
```
![Uploading snapshot21.png…]()

**Comment by yuniers** [comment]
Uploading the screen shot for authorize ownCloud add-on
![snapshot22](https://cloud.githubusercontent.com/assets/1646435/12689845/545e57e0-c6ad-11e5-81aa-cd9d9050aec1.png)

**Comment by alexanderhaensch** [comment]
In my case it does not work with a letsencrypt certificate, but works with comodo.

**Comment by mach-o** [comment]
I'm using a letsencrypt certificate, so perhaps that explains this.

**Comment by alexanderhaensch** [comment]
I was testing with the very same server, same cipher/SSL config but different domainname and cert.
Normally thunderbird does not seem to have problems with letsencrypt.

**Comment by alexanderhaensch** [comment]
It works if you add the root cert from https://letsencrypt.org/certificates/ to Thunderbirds certificate store.

**Comment by mach-o** [comment]
Thanks for the suggested workaround! It didn't change things for me, but perhaps I just don't know how to properly add to the certificate store? I tried adding the pem file using Edit » Preferences » Advanced » Certificates » Authorities » Import … » downloaded pem file » Select all options » Ok. Did I go wrong somewhere in there?

**Comment by powerriegel** [comment]
I'm using a StratSSL cert. I also added intermediate certs. Same problem

**Comment by guillaumev** [comment]
Closing this, please try 1.4. If it's still not working, feel free to reopen.

**Comment by mach-o** [comment]
This fixed it for me! Thanks @guillaumev this is great!
