### ISSUE TITLE
Files more than 150 megabytes?

### ISSUE THREAD

**Issue by my-bam** [guillaumev/owncloud_for_filelink#39]
Filelink not accept files over 150 MB.
How to solve this problem?

**Comment by eidota** [comment]
Any new info on this? We have the same problem here.

**Comment by eidota** [comment]
/components/nsOwncloud.js has an kMaxFileSize constant set to 150 MB. I changed it to 512 MB in my configuration and it workd flawlessly.
Is there any reason to keep this constant at this low value? Could you give us the possibility to set this value in about:config?
