### ISSUE TITLE
Possibility to configure the link adress

### ISSUE THREAD

**Issue by testingtigerwolf** [guillaumev/owncloud_for_filelink#41]
I think to the following use-case :
1. During Filelink first configuration, I have set  the owncloud server address (ex : myAddress.com/owncloud)
2. I want the link communicated to my contact another DNS address (ex : otherAddress.net/owncloud)

**Comment by godfuture** [comment]
I guess you want to reach otherAddress.net over internet. I see two possibilities:
-  This means you need the ownership of this domain. If you do, you could rewrite the URL from this domain to your myAddress.com.
- You use a shortening service: 
http://searchengineland.com/analysis-which-url-shortening-service-should-you-use-17204

This addon could only help you with the second option. But as this should be better done on server, I guess it will not gonna happen.

Cheers

PS: I am not developing it, but just trying to help.

**Comment by guillaumev** [comment]
Sorry, this won't be fixed by this addon.
